=== MirniyPirojok/ItAcademyHomeworks/src/recources/banks-validation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://htp.com/academy"
        xmlns:academy="http://htp.com/academy">
    <element name="banks">
        <complexType>
            <sequence>
                <element name="bank" minOccurs="2" maxOccurs="unbounded" type="academy:Bank"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Bank">
        <sequence>
            <element name="name" type="string"/>
            <element name="bik" type="long"/>
            <element name="address" type="string"/>
        </sequence>
        <attribute name="id" type="long" use="required"/>
    </complexType>
</schema>

=== MirniyPirojok/ItAcademyHomeworks/src/recources/banks.xml
<?xml version="1.0" encoding="UTF-8"?>
<academy:banks
        xmlns:academy="http://htp.com/academy"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://htp.com/academy banks-validation.xsd">

    <bank id="1">
        <name>Priorbank</name>
        <bik>777</bik>
        <address>Nezavisimosti 168</address>
    </bank>
    <bank id="2">
        <name>BNB</name>
        <bik>999</bik>
        <address>Nezavisimosti 175</address>
    </bank>
</academy:banks>
